---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/recommended

parserOptions:
  ecmaVersion: 13
  sourceType: module

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: 0
